[[plugins]]
package = "netlify-plugin-imageengine"

  [plugins.inputs]
  deliveryAddress = "blazing-fast-pics.cdn.imgeng.in"

  [plugins.inputs.directives]
  height = 600
  width = 700
  rotate = 90

[build]
base = "/"          # Explicitly set root directory
publish = "/"       # Where to publish from
command = ""        # Empty if no build needed

[build.environment]
NODE_VERSION = "18"
CI = "true"

[build.processing]
  skip_processing = true  # Skip post-processing

[functions]
  directory = "netlify/functions"  # Default functions directory